# Generated by Django 5.1.4 on 2025-01-04 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='driverModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('driver_id', models.IntegerField(unique=True)),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.routemodel')),
            ],
        ),
    ]
