# Generated by Django 5.1.4 on 2025-01-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='routeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.IntegerField(unique=True)),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
